name: Scala CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5 # uses Java version adopt@1.8 by default
        # with:
        # java-version: adopt@1.11
      - name: Run tests
        run: sbt g8Test
