name: Scala CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # required when running locally with `act`
    env:
      RUNNER_OS: linux

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Run tests
        run: sbt g8Test
